# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1fe04913e9cb189824f1e22da3fcf36df7d6536db925dfd65e1c7dcee4522009b8bf4f10218824f63c17951822ba11e30cd8a4a26a70d76370d87a9abbd36f8

test:
  secret_key_base: 7331017cb178f4034158773a957608fb4ea8b240feda5d1c2d8c3a1027fcbb7d20247500bcee4184b4d45b79aca616f25c951316a6be436893bd2df488e0b350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
